version: "3.9"

services:
  nutri_ledger_pg:
    image: postgres:15-alpine
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - nutri_ledger_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nutriLedger-net

  nutri_ledger_mongo:
    image: mongo:6.0
    ports:
      - "27018:27018"
    volumes:
      - nutri_ledger_mongo_data:/data/db
    networks:
      - nutriLedger-net

  liquibase_nutri_ledger:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - nutri_ledger_pg
    environment:
      POSTGRES_HOST: nutri_ledger_pg
      POSTGRES_PORT: 5434
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../changelog.yaml:/changelog.yaml:ro
      - ../migrations:/migrations:ro
      - ../liquibase.properties:/liquibase.properties:ro
    command: update
    networks:
      - nutriLedger-net

volumes:
  nutri_ledger_pg_data:
    driver: local
  nutri_ledger_mongo_data:
    driver: local

networks:
  nutriLedger-net:
    driver: bridge
